/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.UserEnterprise;

import Business.EcoSystem;
import javax.swing.JPanel;

/**
 *
 * @author jshar
 */
public class InsuranceJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    EcoSystem ecosystem;
    /**
     * Creates new form InsuranceJPanel
     */
    public InsuranceJPanel(JPanel userProcessContainer, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        month3btn = new javax.swing.JRadioButton();
        month6btn = new javax.swing.JRadioButton();
        month9btn = new javax.swing.JRadioButton();
        month12btn = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtAmountToBePay = new javax.swing.JTextField();
        btnPay = new javax.swing.JButton();
        btnGenerateRecipt = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Want Insurance ?");

        jLabel2.setText("Month:");

        month3btn.setText("6 month");
        month3btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                month3btnActionPerformed(evt);
            }
        });

        month6btn.setText("1 year");
        month6btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                month6btnActionPerformed(evt);
            }
        });

        month9btn.setText("2 year");
        month9btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                month9btnActionPerformed(evt);
            }
        });

        month12btn.setText("5 years");
        month12btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                month12btnActionPerformed(evt);
            }
        });

        jLabel4.setText("Plan Type:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Platinum", "Gold", "Silver", "Bronze", " " }));

        jLabel5.setText("Amount to be pay:");

        btnPay.setText("Pay");

        btnGenerateRecipt.setText("Generate Recipt");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(month3btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(month6btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnGenerateRecipt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAmountToBePay))
                                .addGap(50, 50, 50)))
                        .addComponent(month9btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(month12btn)))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(month3btn)
                    .addComponent(month12btn)
                    .addComponent(month6btn)
                    .addComponent(month9btn)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAmountToBePay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnPay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGenerateRecipt)
                .addContainerGap(194, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void month3btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_month3btnActionPerformed
        // TODO add your handling code here:
        if(month3btn.isSelected()) {
            month6btn.setSelected(false);
            month9btn.setSelected(false);
            month12btn.setSelected(false);
        }
    }//GEN-LAST:event_month3btnActionPerformed

    private void month6btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_month6btnActionPerformed
        // TODO add your handling code here:
        if(month6btn.isSelected()) {
            month3btn.setSelected(false);
            month9btn.setSelected(false);
            month12btn.setSelected(false);
        }
    }//GEN-LAST:event_month6btnActionPerformed

    private void month9btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_month9btnActionPerformed
        // TODO add your handling code here:
        if(month9btn.isSelected()) {
            month3btn.setSelected(false);
            month6btn.setSelected(false);
            month12btn.setSelected(false);
        }
    }//GEN-LAST:event_month9btnActionPerformed

    private void month12btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_month12btnActionPerformed
        // TODO add your handling code here:
        if(month12btn.isSelected()) {
            month3btn.setSelected(false);
            month6btn.setSelected(false);
            month9btn.setSelected(false);
        }
    }//GEN-LAST:event_month12btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateRecipt;
    private javax.swing.JButton btnPay;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton month12btn;
    private javax.swing.JRadioButton month3btn;
    private javax.swing.JRadioButton month6btn;
    private javax.swing.JRadioButton month9btn;
    private javax.swing.JTextField txtAmountToBePay;
    // End of variables declaration//GEN-END:variables
}
