/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdmin;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Role.EmergencyAdminRole;
import Business.Role.HospitalAdminRole;
import Business.Role.MedicalServicesAdmin;
import Business.Role.SystemAdminRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import userinterface.dbConn;

/**
 *
 * @author jshar
 */
public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    EcoSystem ecosystem;
    
     Connection conn = dbConn.getConn();
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form ManageEnterpriseAdminJPanel
     */
    

    ManageEnterpriseAdminJPanel(JPanel userProcessContainer, EcoSystem ecosystem) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;

        populateTable();
        populateNetworkComboBox();
    }
 private void populateTable() {
        try{
        String sql ="select * from manage_logins";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        enterpriseJTable.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
    }
    finally {
            
            try{
                rs.close();
                pst.close();
                
            }
            catch(Exception e){
                
            }
        }
    }

    private void populateNetworkComboBox(){
               networkJComboBox.removeAllItems();
        try{
        String sql ="select * from network";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
            System.out.println("*************");
         while (rs.next()) {  
             System.out.println("77777777777");
        networkJComboBox.addItem(rs.getString("net_name"));  
             System.out.println(rs.getString("net_name"));
             System.out.println("555555555555555");
 }
       
    }
    catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
    }
    finally {
            
            try{
                rs.close();
                pst.close();
                
            }
            catch(Exception e){
                
            }
        }
    }
    
    public void populateEnterprise(){
       enterpriseJComboBox.removeAllItems();
        String n_name=networkJComboBox.getSelectedItem().toString();
        
           try{
        String sql ="select * from manage_enter where network_name='"+n_name+"'";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
         while (rs.next()) {  

        enterpriseJComboBox.addItem(rs.getString("enter_type"));  
                }
       
    }
    catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
    }
    finally {
            
            try{
                rs.close();
                pst.close();
                
            }
            catch(Exception e){
                
            }
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseJTable = new javax.swing.JTable();
        submitJButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        passwordJPasswordField = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        networkJComboBox = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        enterpriseJComboBox = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        usernameJTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseJTable.setBackground(new java.awt.Color(204, 255, 204));
        enterpriseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Enterprise Name", "Network", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enterpriseJTable.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(enterpriseJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 94, 523, 95));

        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 120, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("MANAGE ENTERPRISE ADMIN");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 586, -1));
        add(passwordJPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 344, 134, -1));

        jLabel7.setText("Name");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 387, -1, -1));
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 384, 136, -1));

        jLabel8.setText("Network");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 227, -1, -1));

        networkJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkJComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                networkJComboBoxItemStateChanged(evt);
            }
        });
        networkJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJComboBoxActionPerformed(evt);
            }
        });
        add(networkJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 224, 136, -1));

        jLabel9.setText("Enterprise");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 267, -1, -1));

        enterpriseJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        enterpriseJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseJComboBoxActionPerformed(evt);
            }
        });
        add(enterpriseJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 264, 136, -1));

        jLabel10.setText("Username");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 307, -1, -1));
        add(usernameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 304, 136, -1));

        jLabel11.setText("Password");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 347, -1, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icon/enterprisesystemadmin.gif"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 280, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed

    String net_n=networkJComboBox.getSelectedItem().toString();
        String enter_name=enterpriseJComboBox.getSelectedItem().toString();
        String u_name=usernameJTextField.getText();
        String pass=passwordJPasswordField.getText();
        String name=nameJTextField.getText();
        try {
        String sql = " insert into manage_logins values(?,?,?,?,?)";

                pst = conn.prepareStatement(sql);
                pst.setString(1, net_n);
                pst.setString(2, enter_name);
                pst.setString(3, u_name);
                pst.setString(4, pass);
                pst.setString(5, name);
                
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Enterprise Admin Added successfuly");
                populateTable();
                nameJTextField.setText("");
                usernameJTextField.setText("");
                passwordJPasswordField.setText("");
        }
        catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
        }finally{
            try {
              //  rs.close();
                pst.close();
                
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
            }
           

        populateTable();
      //  JOptionPane.showMessageDialog(null, "Enterprise Admin created successfully");
            

    }//GEN-LAST:event_submitJButtonActionPerformed

    private void networkJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJComboBoxActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_networkJComboBoxActionPerformed

    private void networkJComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_networkJComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_networkJComboBoxItemStateChanged

    private void enterpriseJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseJComboBoxActionPerformed
        // TODO add your handling code here:
        System.out.println("00000000000000");
        String n_name=networkJComboBox.getSelectedItem().toString();
        
           try{
        String sql ="select * from manage_enter where network_name='"+n_name+"'";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
         while (rs.next()) {  

        enterpriseJComboBox.addItem(rs.getString("name"));  
                }
       
    }
    catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
    }
    finally {
            
            try{
                rs.close();
                pst.close();
                
            }
            catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_enterpriseJComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox enterpriseJComboBox;
    private javax.swing.JTable enterpriseJTable;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JPasswordField passwordJPasswordField;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration//GEN-END:variables
}
