/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Population.PeopleDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.CovidRole.CovidWorkAreaJPanel;
import userinterface.DoctorRole.DoctorJPanel;
import userinterface.HospitalEnterprise.HospitalWorkAreaJPanel;
import userinterface.SystemAdmin.SystemAdminWorkAreaJPanel;
import userinterface.UserEnterprise.UserRoleWorkAreaJPanel;
import userinterface.UserRegistration.CreateUserAccountJPanel;

/**
 *
 * @author jshar
 */
public class MainFrame extends javax.swing.JFrame {

    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private PeopleDirectory peopleDirectory;
    private OrganizationDirectory organizationDirectory;
    
    Connection conn= dbConn.getConn();
    PreparedStatement pst =null;
    ResultSet rs= null;
    
    public String username=null;
    public String password=null;

    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        system = dB4OUtil.retrieveSystem();
        peopleDirectory = new PeopleDirectory();
        organizationDirectory = new OrganizationDirectory();
        
        
        
        
       // this.setSize(1680, 1050);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        container = new javax.swing.JPanel();
        LoginPanel = new javax.swing.JPanel();
        btnSignUp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1400, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1400, 800));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerSize(0);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(1400, 100));

        btnLogout.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(1258, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setTopComponent(jPanel2);

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setLayout(new java.awt.CardLayout());

        LoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        LoginPanel.setPreferredSize(new java.awt.Dimension(1400, 700));

        btnSignUp.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Are you a new User??");

        txtPassword.setPreferredSize(new java.awt.Dimension(6, 40));

        btnLogin1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnLogin1.setText("LogIn");
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setText("Login");
        jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Username:");
        jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        txtUsername.setMinimumSize(new java.awt.Dimension(6, 30));
        txtUsername.setPreferredSize(new java.awt.Dimension(6, 30));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Password:");
        jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Category:");
        jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Hospital Enterprise", "End User", "Doctor", "Covid Care" }));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icon/Mainframe.gif"))); // NOI18N

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addComponent(btnLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(LoginPanelLayout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(120, Short.MAX_VALUE))))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(btnLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        container.add(LoginPanel, "card2");

        jSplitPane1.setRightComponent(container);

        jPanel1.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

        container.removeAll();
        dB4OUtil.storeSystem(system);
        LoginPanel.setVisible(true);
        container.add(LoginPanel);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        // TODO add your handling code here:
        //        if(txtUsername.getText().isEmpty() || txtPassword.getText().isEmpty()) {
            //            JOptionPane.showMessageDialog(null,"Username and Password field's cannot be empty");
            //            return;
            //        }
        //
        //        else if(system.getUserAccountDirectory().authenticateUser(txtUsername.getText(), txtPassword.getText()) == null) {
            //            JOptionPane.showMessageDialog(null,"Invalid UserName");
            //            return;
            //        }
        //
        //        UserAccount userAccount = system.getUserAccountDirectory().authenticateUser(txtUsername.getText(), txtPassword.getText());
        //
        //        CardLayout layout = (CardLayout) container.getLayout();
        //        container.add("workArea",userAccount.getRole().createWorkArea(container, userAccount, organization, enterprise, network, system));
        //        layout.next(container);

        //        String userName = txtUsername.getText();
        //        // Get Password
        //        String password = txtPassword.getText();
        //
        //
        //        //Step1: Check in the system admin user account directory if you have the user
        //        UserAccount userAccount=system.getUserAccountDirectory().authenticateUser(userName, password);
        //
        //        Enterprise inEnterprise=null;
        //        Organization inOrganization=null;
        //        Network inNetwork = null;
        //
        //        if(userAccount==null){
            //            //Step 2: Go inside each network and check each enterprise
            //            for(Network network:system.getNetworkList()){
                //                //Step 2.a: check against each enterprise
                //                for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
                    //                    userAccount=enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                    //                    if(userAccount==null){
                        //                       //Step 3:check against each organization for each enterprise
                        //                       for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList()){
                            //                           userAccount=organization.getUserAccountDirectory().authenticateUser(userName, password);
                            //                           if(userAccount!=null){
                                //                               inEnterprise=enterprise;
                                //                               inOrganization=organization;
                                //                               inNetwork = network;
                                //                               break;
                                //                           }
                            //                       }
                        //
                        //                    }
                    //                    else{
                        //                       inEnterprise=enterprise;
                        //                       break;
                        //                    }
                    //                    if(inOrganization!=null){
                        //                        break;
                        //                    }
                    //                }
                //                if(inEnterprise!=null){
                    //                    break;
                    //                }
                //            }
            //        }
        //
        //        if(userAccount==null){
            //            JOptionPane.showMessageDialog(null, "Invalid credentials");
            //            return;
            //        }
        //        else{
            //            CardLayout layout = (CardLayout) container.getLayout();
            //            container.add("workArea",userAccount.getRole().createWorkArea(container, userAccount, inOrganization, inEnterprise, inNetwork, system, organizationDirectory));
            //            layout.next(container);
            //        }

        String name=txtUsername.getText();
        String pass=txtPassword.getText();

        String choice=jComboBox1.getSelectedItem().toString();

        switch(choice){
            case "End User":
            String sql = "select * from user_data where username='"+name+"' and password='"+pass+"'";

            try {

                pst =conn.prepareStatement(sql);
                rs= pst.executeQuery();

                while(rs.next())
                {
                    String f_name=rs.getString("first_name");
                    String l_name=rs.getString("last_name");
                    String gender=rs.getString("gender");
                    String address=rs.getString("address");
                    String email=rs.getString("email");
                    String phone=rs.getString("phone");
                    String blood=rs.getString("blood");
                    String weight=rs.getString("weight");
                    String height=rs.getString("height");
                    String username=rs.getString("username");
                    String age=rs.getString("age");

                    UserRoleWorkAreaJPanel ur=new UserRoleWorkAreaJPanel(container,f_name,l_name,gender,address,email,phone,blood,weight,height,username,age);
                    container.add("ur",ur);
                    CardLayout layout=(CardLayout)container.getLayout();
                    layout.next(container);
                }
                JOptionPane.showMessageDialog(null, "Login successful");
                break;

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }finally{

                try {
                    if (rs!=null) {
                        rs.close();
                    }
                    if (pst!=null) {
                        pst.close();
                    }
                    //                    if (conn!=null) {
                        //                      pst.close();
                        //                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
            case "Doctor":

            try {
                sql = "select * from manage_doc where usern='"+name+"' and passw='"+pass+"'";
                pst =conn.prepareStatement(sql);
                rs= pst.executeQuery();

                System.out.println("0000000000000");
                while(rs.next())
                {
                    System.out.println("5555555555");
                    String doc_name=rs.getString("doc_name");
                    String special=rs.getString("special");
                    String location=rs.getString("location");
                    String doc_net=rs.getString("doc_net");
                    String doc_enter=rs.getString("doc_enter");
                    //  String =rs.getString("doc_enter");

                    DoctorJPanel dp=new DoctorJPanel(container,doc_name,special,location,doc_net,doc_enter,name);
                    container.add("dp",dp);
                    CardLayout layout=(CardLayout)container.getLayout();
                    layout.next(container);
                }
                JOptionPane.showMessageDialog(null, "Login successful");
                break;

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }finally{

                try {
                    if (rs!=null) {
                        rs.close();
                    }
                    if (pst!=null) {
                        pst.close();
                    }
                    //                    if (conn!=null) {
                        //                      pst.close();
                        //                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }

            case "Hospital Enterprise":
            sql = "select * from manage_logins where username='"+name+"' and password='"+pass+"'";

            try {

                pst =conn.prepareStatement(sql);
                rs= pst.executeQuery();

                while(rs.next())
                {
                    String net_name=rs.getString("n_name");
                    String emer_name=rs.getString("e_name");

                    HospitalWorkAreaJPanel hw=new HospitalWorkAreaJPanel(container, null, system, null, null, system, organizationDirectory,net_name, emer_name);
                    container.add("hw",hw);
                    CardLayout layout=(CardLayout)container.getLayout();
                    layout.next(container);
                }
                JOptionPane.showMessageDialog(null, "Login successful");
                break;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }finally{
                try {
                    if (rs!=null) {
                        rs.close();
                    }
                    if (pst!=null) {
                        pst.close();
                    }
                    //                    if (conn!=null) {
                        //                      pst.close();
                        //                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
            case "Admin":
            if(name.equals("sysadmin")&&pass.equals("sysadmin"))
            {
                SystemAdminWorkAreaJPanel sa=new SystemAdminWorkAreaJPanel(container);
                container.add("sa",sa);
                CardLayout layout=(CardLayout)container.getLayout();
                layout.next(container);
                JOptionPane.showMessageDialog(null, "Login successful");
                break;
            }
            else{
                JOptionPane.showMessageDialog(null, "Login Failed");
            }
            case "Covid Care":
            sql = "select * from manage_covid where covid_username='"+name+"' and covid_pass='"+pass+"'";

            try {

                pst =conn.prepareStatement(sql);
                rs= pst.executeQuery();

                while(rs.next())
                {
                    String covid_net=rs.getString("covid_net");
                    String covid_enter=rs.getString("covid_enter");

                    CovidWorkAreaJPanel covid=new CovidWorkAreaJPanel(container, null, system, null, null, system, organizationDirectory,name, pass,covid_net,covid_enter);
                    container.add("covid",covid);
                    CardLayout layout=(CardLayout)container.getLayout();
                    layout.next(container);
                }
                JOptionPane.showMessageDialog(null, "Login successful");
                break;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }finally{
                try {
                    if (rs!=null) {
                        rs.close();
                    }
                    if (pst!=null) {
                        pst.close();
                    }
                    //                    if (conn!=null) {
                        //                      pst.close();
                        //                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }

    }//GEN-LAST:event_btnLogin1ActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed

        CreateUserAccountJPanel createUserAccountJPanel=new CreateUserAccountJPanel(container,system,peopleDirectory);
        container.add("createUserAccountJPanel",createUserAccountJPanel);
        CardLayout layout=(CardLayout)container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnSignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JButton btnLogin1;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JPanel container;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
