/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.UserEnterprise;

import Business.EcoSystem;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.dbConn;

/**
 *
 * @author jshar
 */
public class InsuranceJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    EcoSystem ecosystem;
    String f_name=null;
            String l_name=null;
            String gender=null;
            String address=null;
            String email=null;
            String phone=null;
            String blood=null;
            String weight=null;
            String height=null;
            String username=null;
            String age=null;
             Connection conn = dbConn.getConn();
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    /**
     * Creates new form InsuranceJPanel
     */
    public InsuranceJPanel(JPanel userProcessContainer, String f_name,String l_name,String gender,String address,String email,String phone,String blood,String weight,String height,String username,String age) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
       // this.ecosystem = ecosystem;
        this.f_name=f_name;
        this.l_name=l_name;
        this.gender=gender;
        this.address=address;
        this.email=email;
        this.phone=phone;
        this.blood=blood;
        this.weight=weight;
        this.height=height;
        this.username=username;
        this.age=age;
        
    }

    public InsuranceJPanel(JPanel container, String company, String id) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        month6btn = new javax.swing.JRadioButton();
        year1btn = new javax.swing.JRadioButton();
        year2btn = new javax.swing.JRadioButton();
        year5btn = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtAmountToBePay = new javax.swing.JTextField();
        btnPay = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnGenerate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Month:");

        month6btn.setText("6 month");
        month6btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                month6btnActionPerformed(evt);
            }
        });

        year1btn.setText("1 year");
        year1btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year1btnActionPerformed(evt);
            }
        });

        year2btn.setText("2 year");
        year2btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year2btnActionPerformed(evt);
            }
        });

        year5btn.setText("5 years");
        year5btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year5btnActionPerformed(evt);
            }
        });

        jLabel4.setText("Plan Type:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Platinum", "Gold", "Silver", "Bronze" }));

        jLabel5.setText("Amount to be pay:");

        txtAmountToBePay.setEditable(false);
        txtAmountToBePay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountToBePayActionPerformed(evt);
            }
        });

        btnPay.setText("Request Insurance");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("GET INSURANCE ");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icon/health-insurance.jpg"))); // NOI18N

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnGenerate.setText("Generate");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnPay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(month6btn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(year1btn)))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAmountToBePay, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGenerate)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(year2btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(year5btn))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 932, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(jLabel6))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(month6btn)
                    .addComponent(year5btn)
                    .addComponent(year1btn)
                    .addComponent(year2btn)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtAmountToBePay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGenerate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPay))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void month6btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_month6btnActionPerformed
        // TODO add your handling code here:
        if(month6btn.isSelected()) {
            year1btn.setSelected(false);
            year2btn.setSelected(false);
            year5btn.setSelected(false);
        }
    }//GEN-LAST:event_month6btnActionPerformed

    private void year1btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year1btnActionPerformed
        // TODO add your handling code here:
        if(year1btn.isSelected()) {
            month6btn.setSelected(false);
            year2btn.setSelected(false);
            year5btn.setSelected(false);
        }
    }//GEN-LAST:event_year1btnActionPerformed

    private void year2btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year2btnActionPerformed
        // TODO add your handling code here:
        if(year2btn.isSelected()) {
            month6btn.setSelected(false);
            year1btn.setSelected(false);
            year5btn.setSelected(false);
        }
    }//GEN-LAST:event_year2btnActionPerformed

    private void year5btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year5btnActionPerformed
        // TODO add your handling code here:
        if(year5btn.isSelected()) {
            month6btn.setSelected(false);
            year1btn.setSelected(false);
            year2btn.setSelected(false);
        }
    }//GEN-LAST:event_year5btnActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        // TODO add your handling code here:
//        String duration=null;
//        float base;
//        if(month3btn.isSelected()) {
//            duration = "6 months";
//            
//        }
//        else if(month6btn.isSelected()) {
//            duration = "1 year";
//        }
//        else if(month9btn.isSelected()) {
//            duration = "2 years";
//        }
//        else if(month12btn.isSelected()) {
//            duration = "5 years";
//        }
//        String pack=jComboBox1.getSelectedItem().toString();
//        switch(pack)
//        {
//            case "Platinum":
//                
//            case "Gold":
//                    case "Silver":
//                    case "Bronze":
//                        
//                
//            
//        }
        String duration=null;
        
        if(month6btn.isSelected()) {
            duration = "6 months";
            
        }
        else if(year1btn.isSelected()) {
            duration = "1 year";
        }
        else if(year2btn.isSelected()) {
            duration = "2 years";
        }
        else if(year5btn.isSelected()) {
            duration = "5 years";
        }
        String pack=jComboBox1.getSelectedItem().toString();
        
        if(txtAmountToBePay.getText().toString().isEmpty()) {
            JOptionPane.showMessageDialog(null,"Fields cannot be empty");
            return;
        }
        
        float amount=Integer.parseInt(txtAmountToBePay.getText());
        try {
        String sql = " insert into insure_request values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

                pst = conn.prepareStatement(sql);
                pst.setString(1, f_name);
                pst.setString(2, l_name);
                pst.setString(3, gender);
                pst.setString(4, address);
                pst.setString(5, email);
                pst.setString(6, phone);
                pst.setString(7, blood);
                pst.setString(8, weight);
                pst.setString(9, height);
                pst.setString(10, username);
              //  pst.setString(11, password);
                pst.setString(11, age);
                pst.setString(12, duration);
                pst.setString(13, pack);
                pst.setFloat(14, amount);
                pst.setString(15,"Requested");
                
                
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Insurance Requested  successfuly");
                
               
                txtAmountToBePay.setText("");
                
        }
        catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
        }finally{
            try {
              //  rs.close();
                pst.close();
                
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
            }
    }//GEN-LAST:event_btnPayActionPerformed

    private void txtAmountToBePayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountToBePayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountToBePayActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        // TODO add your handling code here:
        int monthvalue = 0;
        int typeValue = 0;
        
        if(!(month6btn.isSelected() || year1btn.isSelected() || year2btn.isSelected() || year5btn.isSelected())) {
            JOptionPane.showMessageDialog(null, "Please select duration");
            return;
        }
        
        if(month6btn.isSelected()) {
            monthvalue = 50;
        }
        else if(year1btn.isSelected()) {
            monthvalue = 70;
        }
        else if(year2btn.isSelected()) {
            monthvalue = 80;
        }
        else if(year5btn.isSelected()) {
            monthvalue = 100;
        }
        
        if(jComboBox1.getSelectedIndex() == 0) {
            typeValue = 600;
        }
        else if(jComboBox1.getSelectedIndex() == 1) {
            typeValue = 425;
        }
        else if(jComboBox1.getSelectedIndex() == 2) {
            typeValue = 375;
        }
        else if(jComboBox1.getSelectedIndex() == 3) {
            typeValue = 200;
        }
        
        int value = monthvalue * typeValue;
        txtAmountToBePay.setText(String.valueOf(value));
    }//GEN-LAST:event_btnGenerateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnPay;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton month6btn;
    private javax.swing.JTextField txtAmountToBePay;
    private javax.swing.JRadioButton year1btn;
    private javax.swing.JRadioButton year2btn;
    private javax.swing.JRadioButton year5btn;
    // End of variables declaration//GEN-END:variables
}
